
name: CI
on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron:  '23 3 * * *'

jobs:
    flake8:
        name: Flake8
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -
            uses: actions/setup-python@v4
            with:
                # matches compat target in setup.py
                python-version: '3.8'
        -   name: "Flake8 test"
            run: |
                python3 -m venv myenv
                source myenv/bin/activate
                python -m pip install wheel
                python -m pip install flake8 flake8-quotes
                python -m flake8 setup.py driver.py y3prediction

    emirge:
        name: Emirge installation
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            #os: [ubuntu-latest, macos-latest]
            os: [ubuntu-latest]

        steps:
        - uses: actions/checkout@v3
        - name: Install emirge
          run: |
            [[ $(uname) == Linux ]] && sudo apt-get update && sudo apt-get install -y openmpi-bin libopenmpi-dev bsdmainutils libgl1-mesa-glx libegl1
            [[ $(uname) == Darwin ]] && brew update && brew install mpich
            ./buildMirge.sh
            cd emirge
            source config/activate_env.sh
            ./version.sh

        - name: Run pylint
          run: |
            source emirge/config/activate_env.sh
            python -m pip install wheel
            python -m pip install pylint pyyaml

            pylint setup.py driver.py y3prediction

        - name: Eager smoke test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test
            ./run.sh

        - name: Eager smoke restart test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test
            ./run_restart.sh

        - name: Eager smoke restart n2 to n7 transition test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test
            ./run_transition.sh

        - name: Numpy smoke test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test
            ./run_numpy.sh

        - name: Lazy smoke test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test
            ./run_lazy.sh

        - name: Compare smoke_test accuracy
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test/viz_data

            TOL_LAZY=1e-2
            TOL_NUMPY=1e-2

            set -x
            for vizfile in $(ls *-eager-*.vtu); do
                lazy_vizfile=$(echo ${vizfile/eager/lazy})
                python ../../emirge/mirgecom/bin/mirgecompare.py --tolerance $TOL_LAZY ${vizfile} ${lazy_vizfile}
                numpy_vizfile=$(echo ${vizfile/eager/numpy})
                python ../../emirge/mirgecom/bin/mirgecompare.py --tolerance $TOL_NUMPY ${vizfile} ${numpy_vizfile}
            done

        - name: Lazy smoke test without wall
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test_nw
            ./run_lazy.sh

        - name: Kitchen sink smoke test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test_ks
            ./run_lazy.sh

        - name: Kitchen sink 3D smoke test
          run: |
            source emirge/config/activate_env.sh
            cd smoke_test_ks_3d/data
            cd ..
            ./run_lazy.sh

